// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPerson() {
  return window['go']['main']['App']['GetPerson']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogConsoleInfo(arg1) {
  return window['go']['main']['App']['LogConsoleInfo'](arg1);
}

export function UpdateLoginCount(arg1) {
  return window['go']['main']['App']['UpdateLoginCount'](arg1);
}
