// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPerson():Promise<main.Person>;

export function Greet(arg1:string):Promise<string>;

export function LogConsoleInfo(arg1:string):Promise<void>;

export function UpdateLoginCount(arg1:main.Person):Promise<main.Person>;
