// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUUsage() {
  return window['go']['sys']['Stats']['GetCPUUsage']();
}

export function Shutdown(arg1) {
  return window['go']['sys']['Stats']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['sys']['Stats']['Startup'](arg1);
}
